// <auto-generated />
using System;
using BTCPayServer.Plugins.ArkPayServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTCPayServer.Plugins.ArkPayServer.Data.Migrations
{
    [DbContext(typeof(ArkPluginDbContext))]
    [Migration("20260911063748_AddCompositionRouteJournal")]
    partial class AddCompositionRouteJournal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BTCPayServer.Plugins.Ark")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTCPayServer.Plugins.ArkPayServer.Data.ArkInvoiceComposition", b =>
                {
                    b.Property<Guid>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("character varying(88)");

                    b.Property<long?>("BaseAmountSats")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)");

                    b.Property<string>("EvmAmount")
                        .HasMaxLength(78)
                        .HasColumnType("character varying(78)");

                    b.Property<string>("EvmClaimAddress")
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)");

                    b.Property<string>("EvmClaimTransactionId")
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)");

                    b.Property<string>("EvmLockTransactionId")
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)");

                    b.Property<string>("EvmObservedAtBlock")
                        .HasMaxLength(78)
                        .HasColumnType("character varying(78)");

                    b.Property<string>("EvmProvenAtBlock")
                        .HasMaxLength(78)
                        .HasColumnType("character varying(78)");

                    b.Property<long?>("EvmProvenBlockTimestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("EvmRefundAddress")
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)");

                    b.Property<string>("EvmTimeoutBlock")
                        .HasMaxLength(78)
                        .HasColumnType("character varying(78)");

                    b.Property<string>("EvmTokenAddress")
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("IngressClaimTransactionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("InvoiceId")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("PaymentHash")
                        .IsConcurrencyToken()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PaymentMethodId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SwapContractAddress")
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)");

                    b.Property<string>("WalletId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RouteId");

                    b.HasIndex("PaymentHash")
                        .IsUnique();

                    b.HasIndex("StoreId", "InvoiceId", "PaymentMethodId");

                    b.ToTable("InvoiceCompositions", "BTCPayServer.Plugins.Ark");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.ArkPayServer.Data.ArkInvoiceCompositionLeg", b =>
                {
                    b.Property<string>("RfqId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FromAmount")
                        .HasMaxLength(78)
                        .HasColumnType("character varying(78)");

                    b.Property<long?>("FundedAmountSats")
                        .HasColumnType("bigint");

                    b.Property<string>("FundingTransactionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("LockupAddress")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("LockupScript")
                        .HasMaxLength(68)
                        .HasColumnType("character varying(68)");

                    b.Property<string>("PayoutScript")
                        .HasMaxLength(68)
                        .HasColumnType("character varying(68)");

                    b.Property<long?>("RefundLocktime")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.Property<string>("SolverPubkey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ToAmount")
                        .HasMaxLength(78)
                        .HasColumnType("character varying(78)");

                    b.Property<long?>("ValidUntil")
                        .HasColumnType("bigint");

                    b.HasKey("RfqId");

                    b.HasIndex("RouteId", "Kind")
                        .IsUnique();

                    b.ToTable("InvoiceCompositionLegs", "BTCPayServer.Plugins.Ark");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkIntentEntity", b =>
                {
                    b.Property<string>("IntentTxId")
                        .HasColumnType("text");

                    b.Property<string>("BatchId")
                        .HasColumnType("text");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<string>("CommitmentTransactionId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeleteProof")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeleteProofMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IntentId")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("PartialForfeits")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("RegisterProof")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegisterProofMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SignerDescriptor")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WalletId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IntentTxId");

                    b.HasIndex("IntentId")
                        .IsUnique()
                        .HasFilter("\"IntentId\" IS NOT NULL");

                    b.ToTable("Intents", "BTCPayServer.Plugins.Ark");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkIntentVtxoEntity", b =>
                {
                    b.Property<string>("IntentTxId")
                        .HasColumnType("text");

                    b.Property<string>("VtxoTransactionId")
                        .HasColumnType("text");

                    b.Property<int>("VtxoTransactionOutputIndex")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IntentTxId", "VtxoTransactionId", "VtxoTransactionOutputIndex");

                    b.HasIndex("VtxoTransactionId", "VtxoTransactionOutputIndex");

                    b.ToTable("IntentVtxos", "BTCPayServer.Plugins.Ark");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkSwapEntity", b =>
                {
                    b.Property<string>("SwapId")
                        .HasColumnType("text");

                    b.Property<string>("WalletId")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ContractScript")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExpectedAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("FailReason")
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Invoice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("Metadata");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SwapType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SwapId", "WalletId");

                    b.HasIndex("WalletId");

                    b.HasIndex("ContractScript", "WalletId");

                    b.ToTable("Swaps", "BTCPayServer.Plugins.Ark");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkWalletContractEntity", b =>
                {
                    b.Property<string>("Script")
                        .HasColumnType("text");

                    b.Property<string>("WalletId")
                        .HasColumnType("text");

                    b.Property<int>("ActivityState")
                        .HasColumnType("integer");

                    b.Property<string>("ContractDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ContractData");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("Metadata");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Script", "WalletId");

                    b.HasIndex("Scope");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletContracts", "BTCPayServer.Plugins.Ark");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkWalletEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccountDescriptor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("TODO_MIGRATION");

                    b.Property<int>("LastUsedIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<string>("Wallet")
                        .HasColumnType("text");

                    b.Property<string>("WalletDestination")
                        .HasColumnType("text");

                    b.Property<int>("WalletType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Wallet")
                        .IsUnique()
                        .HasFilter("\"Wallet\" IS NOT NULL");

                    b.ToTable("Wallets", "BTCPayServer.Plugins.Ark");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkadeSwapIntentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromAssetId")
                        .HasColumnType("text");

                    b.Property<long?>("HtlcLocktime")
                        .HasColumnType("bigint");

                    b.Property<string>("HtlcPubkey")
                        .HasColumnType("text");

                    b.Property<string>("Invoice")
                        .HasColumnType("text");

                    b.Property<string>("MakerDescriptor")
                        .HasColumnType("text");

                    b.Property<long>("OfferAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("OfferHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OnchainPayoutAddress")
                        .HasColumnType("text");

                    b.Property<string>("PaymentHash")
                        .HasColumnType("text");

                    b.Property<string>("Preimage")
                        .HasColumnType("text");

                    b.Property<long?>("RefundLocktime")
                        .HasColumnType("bigint");

                    b.Property<string>("SpentTxid")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SwapAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SwapPkScript")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToAssetId")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("WalletId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("WantAmount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PaymentHash");

                    b.HasIndex("SwapPkScript");

                    b.HasIndex("WalletId", "Status");

                    b.ToTable("ArkadeSwapIntents", "BTCPayServer.Plugins.Ark");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.VtxoEntity", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<int>("TransactionOutputIndex")
                        .HasColumnType("integer");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("ArkTxid")
                        .HasColumnType("text");

                    b.Property<string>("AssetsJson")
                        .HasColumnType("text");

                    b.Property<string>("CommitmentTxids")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ExpiresAtHeight")
                        .HasColumnType("bigint");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("Metadata");

                    b.Property<bool>("Preconfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("Recoverable")
                        .HasColumnType("boolean");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SettledByTransactionId")
                        .HasColumnType("text");

                    b.Property<string>("SpentByTransactionId")
                        .HasColumnType("text");

                    b.Property<bool>("Unrolled")
                        .HasColumnType("boolean");

                    b.HasKey("TransactionId", "TransactionOutputIndex");

                    b.ToTable("Vtxos", "BTCPayServer.Plugins.Ark");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.ArkPayServer.Data.ArkInvoiceCompositionLeg", b =>
                {
                    b.HasOne("BTCPayServer.Plugins.ArkPayServer.Data.ArkInvoiceComposition", null)
                        .WithMany("Legs")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkIntentVtxoEntity", b =>
                {
                    b.HasOne("NArk.Storage.EfCore.Entities.ArkIntentEntity", "Intent")
                        .WithMany("IntentVtxos")
                        .HasForeignKey("IntentTxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NArk.Storage.EfCore.Entities.VtxoEntity", "Vtxo")
                        .WithMany("IntentVtxos")
                        .HasForeignKey("VtxoTransactionId", "VtxoTransactionOutputIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intent");

                    b.Navigation("Vtxo");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkSwapEntity", b =>
                {
                    b.HasOne("NArk.Storage.EfCore.Entities.ArkWalletEntity", "Wallet")
                        .WithMany("Swaps")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NArk.Storage.EfCore.Entities.ArkWalletContractEntity", "Contract")
                        .WithMany("Swaps")
                        .HasForeignKey("ContractScript", "WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkWalletContractEntity", b =>
                {
                    b.HasOne("NArk.Storage.EfCore.Entities.ArkWalletEntity", "Wallet")
                        .WithMany("Contracts")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.ArkPayServer.Data.ArkInvoiceComposition", b =>
                {
                    b.Navigation("Legs");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkIntentEntity", b =>
                {
                    b.Navigation("IntentVtxos");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkWalletContractEntity", b =>
                {
                    b.Navigation("Swaps");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkWalletEntity", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Swaps");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.VtxoEntity", b =>
                {
                    b.Navigation("IntentVtxos");
                });
#pragma warning restore 612, 618
        }
    }
}
