name: nigiri
services:
  # Lightning swap services
  boltz-lnd:
    image: btcpayserver/lnd:v0.19.3-beta
    restart: unless-stopped
    container_name: boltz-lnd
    environment:
      LND_CHAIN: "btc"
      LND_ENVIRONMENT: "regtest"
      LND_EXPLORERURL: "http://nbxplorer:32838/"
      LND_REST_LISTEN_HOST: http://boltz-lnd:8080
      LND_EXTRA_ARGS: |
        bitcoin.node=bitcoind  
        maxpendingchannels=10
        rpclisten=0.0.0.0:10009
        restlisten=boltz-lnd:8080
        bitcoind.rpchost=bitcoin:18443
        bitcoind.rpcuser=admin1
        bitcoind.rpcpass=123
        bitcoind.zmqpubrawblock=tcp://bitcoin:28332
        bitcoind.zmqpubrawtx=tcp://bitcoin:28333
        db.bolt.auto-compact=true
        db.prune-revocation=true
        alias=Ark Labs
        externalip=boltz-lnd:9735
        protocol.option-scid-alias=true
        protocol.wumbo-channels=true
        accept-keysend=true
        minchansize=25000
        noseedbackup=false
        gc-canceled-invoices-on-startup=true
        coin-selection-strategy=random
        protocol.custom-message=513
        protocol.custom-nodeann=39
        protocol.custom-init=39
        no-rest-tls=1
        tlsextradomain=boltz-lnd
        debuglevel=debug
        restcors=*
    volumes:
      - boltz_lnd_datadir:/root/.lnd
    ports:
      - '9736:9735'
      - '10010:10009'
  lnd:
    image: btcpayserver/lnd:v0.19.3-beta
    restart: unless-stopped
    container_name: lnd
    environment:
      LND_CHAIN: "btc"
      LND_ENVIRONMENT: "regtest"
      LND_EXPLORERURL: "http://nbxplorer:32838/"
      LND_REST_LISTEN_HOST: http://lnd:8080
      LND_EXTRA_ARGS: |
        bitcoin.node=bitcoind  
        maxpendingchannels=10
        rpclisten=0.0.0.0:10009
        restlisten=lnd:8080
        bitcoind.rpchost=bitcoin:18443
        bitcoind.rpcuser=admin1
        bitcoind.rpcpass=123
        bitcoind.zmqpubrawblock=tcp://bitcoin:28332
        bitcoind.zmqpubrawtx=tcp://bitcoin:28333
        db.bolt.auto-compact=true
        db.prune-revocation=true
        alias=Ark Labs User
        externalip=lnd:9735
        protocol.option-scid-alias=true
        protocol.wumbo-channels=true
        accept-keysend=true
        minchansize=25000
        noseedbackup=false
        gc-canceled-invoices-on-startup=true
        coin-selection-strategy=random
        protocol.custom-message=513
        protocol.custom-nodeann=39
        protocol.custom-init=39
        no-rest-tls=1
        debuglevel=debug
        restcors=*
        tlsextradomain=lnd
    volumes:
      - lnd_user_datadir:/root/.lnd
    ports:
      - '9735:9735'
      - '10009:10009'

  boltz-fulmine:
    image: kukks/fulmine:v8-preview
    container_name: boltz-fulmine
    environment:
      - FULMINE_ARK_SERVER=http://ark:7070
      - FULMINE_ESPLORA_URL=http://chopsticks:3000
      - FULMINE_NO_MACAROONS=true
      - FULMINE_BOLTZ_URL=http://boltz:9001
      - FULMINE_BOLTZ_WS_URL=ws://boltz:9001
      - FULMINE_DISABLE_TELEMETRY=true
      - FULMINE_UNLOCKER_TYPE=env
      - FULMINE_UNLOCKER_PASSWORD=password
    ports:
      - 7002:7000
      - 7003:7001
    volumes:
      - boltz_fulmine_datadir:/app/data
    restart: unless-stopped

  boltz:
    image: boltz/boltz:ark-v8@sha256:dfb23888998d5fd74f56f9943fde82dd6d04bbbec1b009058b4be43a48ef4eaa
    container_name: boltz
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
      - '9004:9004'
    expose:
      - '9001'
    environment:
      BOLTZ_CONFIG: |
        loglevel = "debug"
        network = "regtest"
        [ark]
        host = "boltz-fulmine"
        port = 7000

        [api]
        host = "0.0.0.0"
        port = 9001
        cors = "*"

        [grpc]
        host = "0.0.0.0"
        port = 9000

        [sidecar]
        [sidecar.grpc]
        host = "0.0.0.0"
        port = 9003

        [sidecar.ws]
        host = "0.0.0.0"
        port = 9004

        [sidecar.api]
        host = "0.0.0.0"
        port = 9005

        [postgres]
        host = "postgres"
        port = 5432
        database = "boltz"
        username = "postgres"
        password = "postgres"

        [swap]
        deferredClaimSymbols = [ "BTC" ]

        [[pairs]]
        base = "ARK"
        quote = "BTC"
        rate = 1
        fee = 0
        swapInFee = 0.00
        maxSwapAmount = 4294967
        minSwapAmount = 1000

        [pairs.timeoutDelta]
        reverse = 1440
        chain=1440
        swapMinimal = 1440
        swapMaximal = 2880
        swapTaproot = 10080

        [[currencies]]
        symbol = "BTC"
        network = "bitcoinRegtest"
        minWalletBalance = 10000000
        minLocalBalance = 10000000
        minRemoteBalance = 10000000
        maxSwapAmount = 4294967
        minSwapAmount = 50000
        maxZeroConfAmount = 100000
        preferredWallet = "core"

        [currencies.chain]
        host = "bitcoin"
        port = 18443
        user = "admin1"
        password = "123"
        zmqpubrawtx = "tcp://bitcoind:28333"
        zmqpubrawblock = "tcp://bitcoind:28332"

        [currencies.lnd]
        host = "boltz-lnd"
        port = 10009
        certpath = "/home/boltz/.lnd/tls.cert"
        macaroonpath = "/home/boltz/.lnd/data/chain/bitcoin/regtest/admin.macaroon"
    volumes:
      - boltz_datadir:/home/boltz/.boltz
      - boltz_lnd_datadir:/home/boltz/.lnd
    entrypoint:
      - sh
      - -c
      - |
        # Wait for postgres to be ready
        until PGPASSWORD=postgres psql -h postgres -U postgres -c '\q' 2>/dev/null; do
          echo "Waiting for postgres..."
          sleep 1
        done
        
        # Create database if it doesn't exist
        PGPASSWORD=$$POSTGRES_PASSWORD psql -h postgres -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'boltz'" | grep -q 1 || \
        PGPASSWORD=$$POSTGRES_PASSWORD psql -h postgres -U postgres -c "CREATE DATABASE boltz"
        
        # Start boltzd
        echo "$$BOLTZ_CONFIG" > /home/boltz/.boltz/boltz.config
        boltzd --datadir /home/boltz/.boltz --configpath /home/boltz/.boltz/boltz.config
    
volumes:
  boltz_datadir:
  boltz_lnd_datadir:
  boltz_fulmine_datadir:
  lnd_user_datadir:
    

networks:
  default:
    name: nigiri
    external: true