name: nigiri
services:
  ark-wallet:
    container_name: ark-wallet
    image: ghcr.io/arkade-os/arkd-wallet:v0.7.0
    environment:
      ARKD_WALLET_ESPLORA_URL: "http://chopsticks:3000"
      ARKD_WALLET_NEUTRINO_PEER: "bitcoin:18444"
      ARKD_WALLET_DATADIR: "./data/regtest"
      ARKD_WALLET_NETWORK: "regtest"
    volumes:
      - ./volumes/ark/wallet:/app/data
    ports:
      - "6060:6060"

  ark:
    container_name: arkd
    image: ghcr.io/arkade-os/arkd:v0.7.0
    depends_on:
      - ark-wallet
    environment:
      ARKD_ROUND_INTERVAL: 10
      ARKD_NETWORK: "regtest"
      ARKD_LOG_LEVEL: "5"
      ARKD_NO_MACAROONS: "true"
      ARKD_VTXO_TREE_EXPIRY: "100" # blocks
      ARKD_SCHEDULER_TYPE: "block"
      ARKD_UNILATERAL_EXIT_DELAY: "512"
      ARKD_BOARDING_EXIT_DELAY: "1024"
      ARKD_DATADIR: "./data/regtest"
      ARKD_WALLET_ADDR: "ark-wallet:6060"
      ARKD_ESPLORA_URL: "http://chopsticks:3000"
      ARKD_VTXO_MIN_AMOUNT: "1"
      ARKD_LIVE_STORE_TYPE: "inmemory"
      ARKD_EVENT_DB_TYPE: "badger"
      ARKD_DB_TYPE: "sqlite"
    volumes:
      - ./volumes/ark/data:/app/data
    ports:
      - "7070:7070"
    restart: unless-stopped

networks:
  default:
    name: nigiri
    external: true